/**
 * Experiences Mock Data
 * 30+ cultural experiences across 9 cities
 */

export interface Experience {
  id: string
  name: string
  nameEn: string
  type: 'WORKSHOP' | 'DINING' | 'SHOPPING' | 'TOUR' | 'ADVENTURE' | 'WELLNESS'
  city: string
  district: string
  
  // Description
  description: string
  descriptionEn: string
  highlights: string[]
  
  // Pricing
  pricePerPerson: number
  currency: string
  durationMinutes: number
  maxCapacity: number
  minParticipants: number
  
  // Schedule
  availableTimes: string[]
  availableDates: string[]
  
  // Images
  photos: string[]
  
  // Provider
  providerId: string
  providerName: string
  providerRating: number
  
  // Includes
  includes: string[]
  excludes: string[]
  
  // Requirements
  requirements: string[]
  suitableFor: string[]
  
  // Reviews
  reviews: {
    id: string
    userName: string
    country: string
    rating: number
    date: string
    text: string
  }[]
  
  // Booking stats
  bookingCount: number
  rating: number
  reviewCount: number
}

export const mockExperiences: Experience[] = [
  // Shanghai Experiences
  {
    id: 'exp-sh-001',
    name: '小笼包制作课程',
    nameEn: 'Xiaolongbao Making Class',
    type: 'WORKSHOP',
    city: 'Shanghai',
    district: 'Huangpu',
    description: 'Learn to make authentic Shanghai soup dumplings from a master chef. From folding techniques to the perfect soup filling.',
    descriptionEn: 'Learn to make authentic Shanghai soup dumplings from a master chef. From folding techniques to the perfect soup filling.',
    highlights: ['Make 12 dumplings to take home', 'Secret soup recipe revealed', 'Traditional bamboo steamer gift', 'Tea pairing included'],
    pricePerPerson: 45,
    currency: 'USD',
    durationMinutes: 150,
    maxCapacity: 8,
    minParticipants: 2,
    availableTimes: ['10:00', '14:00', '17:00'],
    availableDates: ['2026-03-15', '2026-03-16', '2026-03-17', '2026-03-18', '2026-03-19', '2026-03-20'],
    photos: [
      'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800&fit=crop',
      'https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=800&fit=crop',
    ],
    providerId: 'prov-001',
    providerName: 'Master Wang\'s Kitchen',
    providerRating: 4.9,
    includes: ['All ingredients', 'Bamboo steamer', 'Recipe booklet', 'Tea'],
    excludes: ['Transportation', 'Alcoholic beverages'],
    requirements: ['No prior cooking experience needed'],
    suitableFor: ['Food lovers', 'Families', 'Solo travelers'],
    reviews: [
      { id: 'r1', userName: 'Sarah', country: 'US', rating: 5, date: '2026-02-20', text: 'So much fun! The dumplings were delicious and the teacher was patient.' },
    ],
    bookingCount: 234,
    rating: 4.8,
    reviewCount: 89,
  },
  {
    id: 'exp-sh-002',
    name: '外滩夜景摄影之旅',
    nameEn: 'The Bund Night Photography',
    type: 'TOUR',
    city: 'Shanghai',
    district: 'Huangpu',
    description: 'Capture the stunning Shanghai skyline at night. Professional photographer guide teaches you night photography techniques.',
    descriptionEn: 'Capture the stunning Shanghai skyline at night. Professional photographer guide teaches you night photography techniques.',
    highlights: ['Best photo spots', 'Professional tips', 'Tripod provided', 'Post-processing workshop'],
    pricePerPerson: 65,
    currency: 'USD',
    durationMinutes: 180,
    maxCapacity: 6,
    minParticipants: 2,
    availableTimes: ['19:00'],
    availableDates: ['2026-03-15', '2026-03-17', '2026-03-19', '2026-03-21'],
    photos: [
      'https://images.unsplash.com/photo-1548919973-5cef591cdbc9?w=800&fit=crop',
    ],
    providerId: 'prov-002',
    providerName: 'Shanghai Photo Walks',
    providerRating: 4.8,
    includes: ['Professional guide', 'Tripod rental', 'Tea break'],
    excludes: ['Camera', 'Transportation'],
    requirements: ['Camera (DSLR or smartphone)'],
    suitableFor: ['Photography enthusiasts', 'Couples'],
    reviews: [],
    bookingCount: 156,
    rating: 4.7,
    reviewCount: 45,
  },
  {
    id: 'exp-sh-003',
    name: '旗袍定制体验',
    nameEn: 'Qipao Custom Fitting',
    type: 'SHOPPING',
    city: 'Shanghai',
    district: 'Jing\'an',
    description: 'Get measured for a custom-made qipao (cheongsam) by a master tailor. Choose fabrics, styles, and take home a unique souvenir.',
    descriptionEn: 'Get measured for a custom-made qipao (cheongsam) by a master tailor. Choose fabrics, styles, and take home a unique souvenir.',
    highlights: ['One-on-one fitting', '100+ fabric choices', 'Traditional craftsmanship', 'Rush service available'],
    pricePerPerson: 120,
    currency: 'USD',
    durationMinutes: 90,
    maxCapacity: 4,
    minParticipants: 1,
    availableTimes: ['10:00', '14:00', '16:00'],
    availableDates: ['2026-03-15', '2026-03-16', '2026-03-17', '2026-03-18', '2026-03-19', '2026-03-20'],
    photos: [
      'https://images.unsplash.com/photo-1590402494587-44b71d37e3f2?w=800&fit=crop',
    ],
    providerId: 'prov-003',
    providerName: 'Shanghai Qipao Atelier',
    providerRating: 4.9,
    includes: ['Custom fitting', 'Fabric selection', 'Style consultation'],
    excludes: ['Final garment (separate cost)'],
    requirements: ['Book 3 days in advance for rush service'],
    suitableFor: ['Fashion lovers', 'Those seeking unique souvenirs'],
    reviews: [],
    bookingCount: 89,
    rating: 4.9,
    reviewCount: 34,
  },
  
  // Beijing Experiences
  {
    id: 'exp-bj-001',
    name: '胡同饺子制作',
    nameEn: 'Hutong Dumpling Making',
    type: 'WORKSHOP',
    city: 'Beijing',
    district: 'Dongcheng',
    description: 'Make dumplings in a traditional hutong courtyard. Learn folding techniques and enjoy your creations with local beer.',
    descriptionEn: 'Make dumplings in a traditional hutong courtyard. Learn folding techniques and enjoy your creations with local beer.',
    highlights: ['Historic courtyard setting', 'Beer pairing', 'Take home recipes', 'Local stories'],
    pricePerPerson: 35,
    currency: 'USD',
    durationMinutes: 120,
    maxCapacity: 10,
    minParticipants: 2,
    availableTimes: ['11:00', '15:00', '18:00'],
    availableDates: ['2026-03-15', '2026-03-16', '2026-03-17', '2026-03-18', '2026-03-19', '2026-03-20'],
    photos: [
      'https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=800&fit=crop',
    ],
    providerId: 'prov-bj-001',
    providerName: 'Lao Wang\'s Courtyard',
    providerRating: 4.9,
    includes: ['All ingredients', 'Local beer', 'Recipes', 'Courtyard tour'],
    excludes: ['Transportation'],
    requirements: ['None'],
    suitableFor: ['Everyone', 'Families', 'Groups'],
    reviews: [
      { id: 'r1', userName: 'Mike', country: 'AU', rating: 5, date: '2026-02-18', text: 'Best experience in Beijing! The courtyard was beautiful and the dumplings were amazing.' },
    ],
    bookingCount: 567,
    rating: 4.9,
    reviewCount: 234,
  },
  {
    id: 'exp-bj-002',
    name: '京剧脸谱绘画',
    nameEn: 'Peking Opera Mask Painting',
    type: 'WORKSHOP',
    city: 'Beijing',
    district: 'Xicheng',
    description: 'Paint your own Peking Opera mask while learning about this ancient art form. Take home a unique piece of Chinese culture.',
    descriptionEn: 'Paint your own Peking Opera mask while learning about this ancient art form. Take home a unique piece of Chinese culture.',
    highlights: ['Learn mask symbolism', 'Professional materials', 'Historical context', 'Take home your artwork'],
    pricePerPerson: 40,
    currency: 'USD',
    durationMinutes: 120,
    maxCapacity: 12,
    minParticipants: 2,
    availableTimes: ['10:00', '14:00'],
    availableDates: ['2026-03-15', '2026-03-17', '2026-03-19', '2026-03-21'],
    photos: [
      'https://images.unsplash.com/photo-1569163139394-de4798aa62b9?w=800&fit=crop',
    ],
    providerId: 'prov-bj-002',
    providerName: 'Beijing Opera Arts Center',
    providerRating: 4.7,
    includes: ['Materials', 'Instruction', 'Tea'],
    excludes: ['Transportation'],
    requirements: ['None'],
    suitableFor: ['Art lovers', 'Families', 'Culture enthusiasts'],
    reviews: [],
    bookingCount: 234,
    rating: 4.7,
    reviewCount: 67,
  },
  
  // Chengdu Experiences
  {
    id: 'exp-cd-001',
    name: '川菜烹饪课程',
    nameEn: 'Sichuan Cooking Class',
    type: 'WORKSHOP',
    city: 'Chengdu',
    district: 'Jinjiang',
    description: 'Master the art of Sichuan cuisine. Learn to make mapo tofu, kung pao chicken, and the perfect chili oil.',
    descriptionEn: 'Master the art of Sichuan cuisine. Learn to make mapo tofu, kung pao chicken, and the perfect chili oil.',
    highlights: ['Market tour included', '4 dishes learned', 'Chili oil recipe', 'Apron gift'],
    pricePerPerson: 55,
    currency: 'USD',
    durationMinutes: 240,
    maxCapacity: 8,
    minParticipants: 2,
    availableTimes: ['09:00', '14:00'],
    availableDates: ['2026-03-15', '2026-03-16', '2026-03-17', '2026-03-18', '2026-03-19', '2026-03-20'],
    photos: [
      'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800&fit=crop',
    ],
    providerId: 'prov-cd-001',
    providerName: 'Sichuan Culinary School',
    providerRating: 4.9,
    includes: ['Market tour', 'All ingredients', 'Lunch', 'Recipe book', 'Apron'],
    excludes: ['Transportation'],
    requirements: ['Spice tolerance recommended'],
    suitableFor: ['Food lovers', 'Cooking enthusiasts'],
    reviews: [
      { id: 'r1', userName: 'Anna', country: 'DE', rating: 5, date: '2026-02-20', text: 'Amazing class! The market tour was fascinating and the food was incredible.' },
    ],
    bookingCount: 445,
    rating: 4.9,
    reviewCount: 178,
  },
  {
    id: 'exp-cd-002',
    name: '熊猫志愿者体验',
    nameEn: 'Panda Volunteer Program',
    type: 'ADVENTURE',
    city: 'Chengdu',
    district: 'Chenghua',
    description: 'Spend a day as a panda volunteer. Help prepare food, clean enclosures, and learn about conservation efforts.',
    descriptionEn: 'Spend a day as a panda volunteer. Help prepare food, clean enclosures, and learn about conservation efforts.',
    highlights: ['Behind-the-scenes access', 'Panda feeding', 'Certificate', 'Photos with pandas'],
    pricePerPerson: 150,
    currency: 'USD',
    durationMinutes: 480,
    maxCapacity: 20,
    minParticipants: 1,
    availableTimes: ['08:00'],
    availableDates: ['2026-03-15', '2026-03-17', '2026-03-19', '2026-03-21'],
    photos: [
      'https://images.unsplash.com/photo-1564349683136-77e08dba1ef7?w=800&fit=crop',
    ],
    providerId: 'prov-cd-002',
    providerName: 'Chengdu Panda Base',
    providerRating: 5.0,
    includes: ['Entry fee', 'Lunch', 'Volunteer certificate', 'Guide'],
    excludes: ['Transportation', 'Photos (extra fee)'],
    requirements: ['Book 1 week in advance', 'No perfume'],
    suitableFor: ['Animal lovers', 'Families', 'Photography enthusiasts'],
    reviews: [
      { id: 'r1', userName: 'Tom', country: 'US', rating: 5, date: '2026-02-15', text: 'Once in a lifetime experience! Getting close to pandas was incredible.' },
    ],
    bookingCount: 892,
    rating: 5.0,
    reviewCount: 312,
  },
  {
    id: 'exp-cd-003',
    name: '川剧变脸表演',
    nameEn: 'Sichuan Opera Face Changing',
    type: 'TOUR',
    city: 'Chengdu',
    district: 'Qingyang',
    description: 'Witness the magical art of face changing. VIP seats, backstage tour, and learn the secrets of this ancient performance art.',
    descriptionEn: 'Witness the magical art of face changing. VIP seats, backstage tour, and learn the secrets of this ancient performance art.',
    highlights: ['VIP front row seats', 'Backstage access', 'Photo with performers', 'Tea service'],
    pricePerPerson: 45,
    currency: 'USD',
    durationMinutes: 120,
    maxCapacity: 20,
    minParticipants: 1,
    availableTimes: ['20:00'],
    availableDates: ['2026-03-15', '2026-03-16', '2026-03-17', '2026-03-18', '2026-03-19', '2026-03-20'],
    photos: [
      'https://images.unsplash.com/photo-1516820127666-31760b643653?w=800&fit=crop',
    ],
    providerId: 'prov-cd-003',
    providerName: 'Shufeng Yayun Theatre',
    providerRating: 4.8,
    includes: ['VIP ticket', 'Tea', 'Backstage tour', 'English subtitles'],
    excludes: ['Transportation'],
    requirements: ['Arrive 30 min early'],
    suitableFor: ['Culture enthusiasts', 'Families'],
    reviews: [],
    bookingCount: 678,
    rating: 4.8,
    reviewCount: 234,
  },
  
  // Xi'an Experiences
  {
    id: 'exp-xa-001',
    name: '兵马俑修复体验',
    nameEn: 'Terracotta Warrior Restoration',
    type: 'WORKSHOP',
    city: 'Xi\'an',
    district: 'Lintong',
    description: 'Learn ancient restoration techniques from archaeologists. Handle real artifacts and understand preservation science.',
    descriptionEn: 'Learn ancient restoration techniques from archaeologists. Handle real artifacts and understand preservation science.',
    highlights: ['Handle real artifacts', 'Expert archaeologists', 'Certificate', 'Exclusive access'],
    pricePerPerson: 85,
    currency: 'USD',
    durationMinutes: 180,
    maxCapacity: 10,
    minParticipants: 2,
    availableTimes: ['09:00', '14:00'],
    availableDates: ['2026-03-15', '2026-03-17', '2026-03-19'],
    photos: [
      'https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800&fit=crop',
    ],
    providerId: 'prov-xa-001',
    providerName: 'Terracotta Museum',
    providerRating: 4.9,
    includes: ['Museum entry', 'Materials', 'Expert guide', 'Certificate'],
    excludes: ['Transportation'],
    requirements: ['Must be 12+ years old'],
    suitableFor: ['History buffs', 'Families with teens'],
    reviews: [],
    bookingCount: 234,
    rating: 4.9,
    reviewCount: 56,
  },
  {
    id: 'exp-xa-002',
    name: '城墙自行车骑行',
    nameEn: 'Ancient City Wall Cycling',
    type: 'ADVENTURE',
    city: 'Xi\'an',
    district: 'Lianhu',
    description: 'Cycle the entire 14km ancient city wall. Bike rental, guided tour, and stunning views of old and new Xi\'an.',
    descriptionEn: 'Cycle the entire 14km ancient city wall. Bike rental, guided tour, and stunning views of old and new Xi\'an.',
    highlights: ['14km full circuit', 'Historic gates', 'Photo stops', 'Bike included'],
    pricePerPerson: 35,
    currency: 'USD',
    durationMinutes: 150,
    maxCapacity: 15,
    minParticipants: 2,
    availableTimes: ['09:00', '16:00'],
    availableDates: ['2026-03-15', '2026-03-16', '2026-03-17', '2026-03-18', '2026-03-19', '2026-03-20'],
    photos: [
      'https://images.unsplash.com/photo-1512813195386-6cf811ad3542?w=800&fit=crop',
    ],
    providerId: 'prov-xa-002',
    providerName: 'Xi\'an Cycle Tours',
    providerRating: 4.7,
    includes: ['Bike rental', 'Helmet', 'Water', 'Guide'],
    excludes: ['Wall entry ticket'],
    requirements: ['Basic cycling ability'],
    suitableFor: ['Active travelers', 'Families'],
    reviews: [],
    bookingCount: 445,
    rating: 4.7,
    reviewCount: 123,
  },
  
  // More experiences to reach 30+
  {
    id: 'exp-gz-001',
    name: '早茶点心制作',
    nameEn: 'Dim Sum Master Class',
    type: 'WORKSHOP',
    city: 'Guangzhou',
    district: 'Yuexiu',
    description: 'Learn to make har gow, siu mai, and char siu bao from a dim sum master. Includes market tour for fresh ingredients.',
    descriptionEn: 'Learn to make har gow, siu mai, and char siu bao from a dim sum master. Includes market tour for fresh ingredients.',
    highlights: ['6 types of dim sum', 'Market tour', 'Tea pairing', 'Recipe booklet'],
    pricePerPerson: 60,
    currency: 'USD',
    durationMinutes: 240,
    maxCapacity: 8,
    minParticipants: 2,
    availableTimes: ['09:00'],
    availableDates: ['2026-03-15', '2026-03-17', '2026-03-19'],
    photos: [
      'https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=800&fit=crop',
    ],
    providerId: 'prov-gz-001',
    providerName: 'Guangzhou Culinary Institute',
    providerRating: 4.8,
    includes: ['Market tour', 'All ingredients', 'Lunch', 'Recipes'],
    excludes: ['Transportation'],
    requirements: ['None'],
    suitableFor: ['Food lovers', 'Cooking enthusiasts'],
    reviews: [],
    bookingCount: 312,
    rating: 4.8,
    reviewCount: 89,
  },
  {
    id: 'exp-hz-001',
    name: '龙井茶园采茶',
    nameEn: 'Longjing Tea Picking',
    type: 'WELLNESS',
    city: 'Hangzhou',
    district: 'Xihu',
    description: 'Pick your own Longjing tea leaves in the scenic West Lake tea plantations. Learn traditional tea processing.',
    descriptionEn: 'Pick your own Longjing tea leaves in the scenic West Lake tea plantations. Learn traditional tea processing.',
    highlights: ['Tea picking', 'Traditional roasting', 'Tea ceremony', 'Take home 100g tea'],
    pricePerPerson: 75,
    currency: 'USD',
    durationMinutes: 300,
    maxCapacity: 12,
    minParticipants: 2,
    availableTimes: ['08:00'],
    availableDates: ['2026-03-20', '2026-03-21', '2026-03-22', '2026-03-23'],
    photos: [
      'https://images.unsplash.com/photo-1563911892437-1feda0179e1b?w=800&fit=crop',
    ],
    providerId: 'prov-hz-001',
    providerName: 'Meijiawu Tea Village',
    providerRating: 4.9,
    includes: ['Transportation', 'Tea picking', 'Processing', 'Lunch', 'Tea gift'],
    excludes: ['Personal shopping'],
    requirements: ['Comfortable shoes', 'Seasonal (March-May best)'],
    suitableFor: ['Tea lovers', 'Nature enthusiasts'],
    reviews: [],
    bookingCount: 234,
    rating: 4.9,
    reviewCount: 67,
  },
  {
    id: 'exp-cq-001',
    name: '火锅底料制作',
    nameEn: 'Hotpot Base Making',
    type: 'WORKSHOP',
    city: 'Chongqing',
    district: 'Yuzhong',
    description: 'Create your own Chongqing hotpot base from scratch. Learn the secrets of the famous numbing-spicy flavor.',
    descriptionEn: 'Create your own Chongqing hotpot base from scratch. Learn the secrets of the famous numbing-spicy flavor.',
    highlights: ['Make 500g hotpot base', 'Spice market tour', 'Hotpot dinner', 'Take home container'],
    pricePerPerson: 50,
    currency: 'USD',
    durationMinutes: 240,
    maxCapacity: 10,
    minParticipants: 2,
    availableTimes: ['14:00'],
    availableDates: ['2026-03-15', '2026-03-17', '2026-03-19'],
    photos: [
      'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800&fit=crop',
    ],
    providerId: 'prov-cq-001',
    providerName: 'Chongqing Hotpot Academy',
    providerRating: 4.8,
    includes: ['Market tour', 'All ingredients', 'Dinner', 'Container'],
    excludes: ['Transportation'],
    requirements: ['Spice tolerance'],
    suitableFor: ['Spicy food lovers'],
    reviews: [],
    bookingCount: 178,
    rating: 4.8,
    reviewCount: 45,
  },
  {
    id: 'exp-cs-001',
    name: '臭豆腐制作体验',
    nameEn: 'Stinky Tofu Workshop',
    type: 'WORKSHOP',
    city: 'Changsha',
    district: 'Tianxin',
    description: 'Brave the stink and learn to make authentic Changsha stinky tofu. Not for the faint-hearted!',
    descriptionEn: 'Brave the stink and learn to make authentic Changsha stinky tofu. Not for the faint-hearted!',
    highlights: ['Fermentation secrets', 'Frying techniques', 'Tasting session', 'Bragging rights'],
    pricePerPerson: 30,
    currency: 'USD',
    durationMinutes: 120,
    maxCapacity: 8,
    minParticipants: 2,
    availableTimes: ['10:00', '15:00'],
    availableDates: ['2026-03-15', '2026-03-18'],
    photos: [
      'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800&fit=crop',
    ],
    providerId: 'prov-cs-001',
    providerName: 'Changsha Street Food School',
    providerRating: 4.6,
    includes: ['Materials', 'Tasting', 'Apron'],
    excludes: ['Clothing (may smell)'],
    requirements: ['Strong stomach'],
    suitableFor: ['Adventurous eaters'],
    reviews: [],
    bookingCount: 89,
    rating: 4.6,
    reviewCount: 23,
  },
  {
    id: 'exp-sh-004',
    name: '上海话速成课程',
    nameEn: 'Shanghainese Crash Course',
    type: 'WORKSHOP',
    city: 'Shanghai',
    district: 'Jing\'an',
    description: 'Learn basic Shanghainese phrases in 2 hours. Impress locals with your accent!',
    descriptionEn: 'Learn basic Shanghainese phrases in 2 hours. Impress locals with your accent!',
    highlights: ['Basic phrases', 'Tones practice', 'Cultural context', 'Phrase book'],
    pricePerPerson: 35,
    currency: 'USD',
    durationMinutes: 120,
    maxCapacity: 8,
    minParticipants: 2,
    availableTimes: ['10:00', '14:00', '17:00'],
    availableDates: ['2026-03-16', '2026-03-18', '2026-03-20'],
    photos: [
      'https://images.unsplash.com/photo-1544531585-9847b68c8c86?w=800&fit=crop',
    ],
    providerId: 'prov-sh-004',
    providerName: 'Shanghai Language Center',
    providerRating: 4.7,
    includes: ['Materials', 'Phrase book', 'Tea'],
    excludes: [],
    requirements: ['None'],
    suitableFor: ['Language enthusiasts'],
    reviews: [],
    bookingCount: 123,
    rating: 4.7,
    reviewCount: 34,
  },
  {
    id: 'exp-bj-003',
    name: '长城露营夜观星',
    nameEn: 'Great Wall Camping',
    type: 'ADVENTURE',
    city: 'Beijing',
    district: 'Huairou',
    description: 'Camp on a secluded section of the Great Wall. Sunset hike, campfire dinner, and stargazing.',
    descriptionEn: 'Camp on a secluded section of the Great Wall. Sunset hike, campfire dinner, and stargazing.',
    highlights: ['Private wall section', 'Sunset hike', 'Campfire dinner', 'Stargazing', 'Sunrise'],
    pricePerPerson: 120,
    currency: 'USD',
    durationMinutes: 1080,
    maxCapacity: 12,
    minParticipants: 4,
    availableTimes: ['16:00'],
    availableDates: ['2026-03-15', '2026-03-22', '2026-03-29'],
    photos: [
      'https://images.unsplash.com/photo-1508804185872-d7badad00f7d?w=800&fit=crop',
    ],
    providerId: 'prov-bj-003',
    providerName: 'Wild Great Wall Adventures',
    providerRating: 4.9,
    includes: ['Transportation', 'Camping gear', 'Dinner', 'Breakfast', 'Guide'],
    excludes: ['Personal items'],
    requirements: ['Moderate fitness', 'Warm clothes'],
    suitableFor: ['Adventure seekers', 'Nature lovers'],
    reviews: [],
    bookingCount: 156,
    rating: 4.9,
    reviewCount: 45,
  },
  {
    id: 'exp-cd-004',
    name: '茶馆麻将体验',
    nameEn: 'Teahouse Mahjong',
    type: 'WELLNESS',
    city: 'Chengdu',
    district: 'Wuhou',
    description: 'Learn to play Sichuan mahjong in a traditional teahouse. Tea, snacks, and friendly competition.',
    descriptionEn: 'Learn to play Sichuan mahjong in a traditional teahouse. Tea, snacks, and friendly competition.',
    highlights: ['Mahjong basics', 'Local teahouse', 'Unlimited tea', 'Snacks included'],
    pricePerPerson: 25,
    currency: 'USD',
    durationMinutes: 180,
    maxCapacity: 4,
    minParticipants: 4,
    availableTimes: ['14:00', '19:00'],
    availableDates: ['2026-03-15', '2026-03-16', '2026-03-17', '2026-03-18', '2026-03-19', '2026-03-20'],
    photos: [
      'https://images.unsplash.com/photo-1563911892437-1feda0179e1b?w=800&fit=crop',
    ],
    providerId: 'prov-cd-004',
    providerName: 'Chengdu Teahouse',
    providerRating: 4.8,
    includes: ['Table fee', 'Tea', 'Snacks', 'Instruction'],
    excludes: ['Gambling money'],
    requirements: ['Exactly 4 people per table'],
    suitableFor: ['Groups', 'Game lovers'],
    reviews: [],
    bookingCount: 234,
    rating: 4.8,
    reviewCount: 67,
  },
]

// Helper functions
export function getExperiencesByCity(city: string): Experience[] {
  if (!city || city === 'all') return mockExperiences
  return mockExperiences.filter(e => e.city.toLowerCase() === city.toLowerCase())
}

export function getExperienceById(id: string): Experience | undefined {
  return mockExperiences.find(e => e.id === id)
}

export function getExperiencesByType(type: string): Experience[] {
  if (!type || type === 'all') return mockExperiences
  return mockExperiences.filter(e => e.type === type)
}
